spring.application.name=bank
server.port=8080

spring.config.import=classpath:application-auth.properties

# DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
# Mapper ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.baas.bank.user.dto,com.baas.bank.oauth2.dto

#Redis
spring.data.redis.host:${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

# Mail Send - Gmail Setting
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.rootUrl=${ROOT_URL}
spring.mail.username=${EMAIL_ID}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.nickname=BaaS


# JWT
jwt.access-token.name=ACCESS_TOKEN
# 10\uBD84 (\uBC00\uB9AC\uCD08 \uB2E8\uC704)
jwt.access-token.expiry=600000
jwt.refresh-token.name=REFRESH_TOKEN
# 1\uC77C (\uBC00\uB9AC\uCD08 \uB2E8\uC704)
jwt.refresh-token.expiry=86400000

spring.jwt.secret=${JWT_SECRET}
#registration
spring.security.oauth2.client.registration.baas.client-name=baas
spring.security.oauth2.client.registration.baas.provider=baas
spring.security.oauth2.client.registration.baas.client-id=0f022a40-9f67-49e1-8639-e78a5da5be11
spring.security.oauth2.client.registration.baas.client-secret=secret
spring.security.oauth2.client.registration.baas.redirect-uri=http://localhost:8080/login/oauth2/code/baas
spring.security.oauth2.client.registration.baas.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.baas.scope=profile,email,phone

#provider
spring.security.oauth2.client.provider.baas.authorization-uri=http://localhost:9000/oauth2/authorize
spring.security.oauth2.client.provider.baas.token-uri=http://localhost:9000/oauth2/token
spring.security.oauth2.client.provider.baas.user-info-uri=http://localhost:9001/me
spring.security.oauth2.client.provider.baas.jwk-set-uri=http://localhost:9000/oauth2/jwks
spring.security.oauth2.client.provider.baas.user-name-attribute=response
