spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}


# 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ## 레디스 설정
  data:
    redis:
      host: localhost
      port: 6379


  security:
    oauth2:
      client:
        registration:
          baas: # [식별자]
            client-name: "BaaS Banking Login"
            client-id: "0f022a40-9f67-49e1-8639-e78a5da5be11"
            client-secret: "secret"
            redirect-uri: "http://localhost:8080/login/oauth2/code/baas"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
              - phone
            provider: baas # 아래 provider 설정과 연결

        provider:
          baas: # [식별자]
            # 1. 인증 서버 (로그인 화면, 토큰 발급) -> 포트 9000
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks

            # 2. 리소스 서버 (유저 정보 조회) -> 포트 9001
            user-info-uri: http://localhost:9001/me

            # 3. 유저 식별자 키값
            user-name-attribute: response

mybatis:
  type-aliases-package: com.baas.securities.repository.entity
  configuration:
    map-underscore-to-camel-case: true
    # SQL 로그에 ? 대신 실제 파라미터 값을 보이게 함
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    # MyBatis SQL 로그를 출력
    org.mybatis: DEBUG
    # (선택) SQL 실행 파라미터 로그를 보고 싶다면 아래도 추가
    jdbc.sqlonly: DEBUG
    jdbc.sqltiming: DEBUG
    jdbc.resultset: TRACE
    jdbc.audit: DEBUG
