spring.application.name=securities
APP_KEY = PSTvMUyI6k30YJQhZG6LcPfTLVsRUL1na8S2
APP_SECRET = 7roQMTPw1zW5WfWF9ZwO5cRJ0PdKn5QwfbwFlWKHxKzzdG8kwOFXfJ5eIh9k/AVmwrBKnCX5I186imJyH1Fx7jTDT09rQnlSyT3/+enxgeCMMGhcPTsHUWqRhs78KgKTv/ZdjgTEyEpH3huApIc+5FhZwVV6fqFUuh6P8X11tTaTCcGiy48=
HTTP_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImU1YzNmZTMzLTM0OTUtNDUxMy04NDViLTI3YWM5NGMzZDg3ZCIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc2MDkzOTU0OCwiaWF0IjoxNzYwODUzMTQ4LCJqdGkiOiJQU1R2TVV5STZrMzBZSlFoWkc2TGNQZlRMVnNSVUwxbmE4UzIifQ.2aq4O44F80XBobcfsAhjeS0D9aZwDrEhrLwm7stzsGQ-3jpZrBshs3-aVYzkqQzdYtq36LUQGxcjGRgc5u-OBw

KIS_HTTP_DOMAIN = https://openapi.koreainvestment.com:9443